### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/span#27]
Happened with SPAN version `span-0.12.0.dev.4671.jar` built on 2 Feb 20 09:24. 
```
[Feb 28, 2020 13:03:28] Model fit: recalculating /mnt/stripe/shpynov/span-noise-experiment/H3K27ac/span/fit/OD7_k27ac_hg19_9.5_1_200.span: [FAILED] after 9.663 min
Caused by: ERROR
kotlin.KotlinNullPointerException
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at org.jetbrains.bio.viktor.F64Array.getV(F64Array.kt)
        at org.jetbrains.bio.statistics.hmm.HMMInternals.logBackward(Internals.kt:83)
        at org.jetbrains.bio.statistics.hmm.HMMIterationContext$expect$2.run(HMMIterationContext.kt:48)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
        at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
        at org.jetbrains.bio.statistics.hmm.HMMIterationContext.expect(HMMIterationContext.kt:40)
        at org.jetbrains.bio.statistics.IterationContext.iterate(ClassificationModel.kt:301)
        at org.jetbrains.bio.statistics.hmm.MLAbstractHMM$fit$1.invoke(MLAbstractHMM.kt:80)
        at org.jetbrains.bio.statistics.hmm.MLAbstractHMM$fit$1.invoke(MLAbstractHMM.kt:17)
        at org.jetbrains.bio.statistics.hmm.MLAbstractHMM$sam$java_util_function_Consumer$0.accept(MLAbstractHMM.kt)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

kotlin.KotlinNullPointerException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at org.jetbrains.bio.statistics.hmm.MLAbstractHMM.fit(MLAbstractHMM.kt:80)
        at org.jetbrains.bio.statistics.hmm.MLFreeNBHMM.fit(MLFreeNBHMM.kt:46)
        at org.jetbrains.bio.statistics.Fitter$DefaultImpls.fit(ClassificationModel.kt:193)
        at org.jetbrains.bio.statistics.Fitter$multiStarted$1.fit(ClassificationModel.kt:242)
        at org.jetbrains.bio.statistics.Fitter$DefaultImpls.fit$default(ClassificationModel.kt:186)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.calculateModel(SpanModelFitExperiment.kt:370)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.access$calculateModel(SpanModelFitExperiment.kt:329)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$getOrLoadResults$1.invoke(SpanModelFitExperiment.kt:412)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$getOrLoadResults$1.invoke(SpanModelFitExperiment.kt:329)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$$special$$inlined$time$lambda$1.invoke(PathExtensions.kt:326)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$$special$$inlined$time$lambda$1.invoke(PathExtensions.kt)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt:467)
        at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt)
        at org.jetbrains.bio.util.LockManager.synchronized(LockManager.kt:39)
        at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate(PathExtensions.kt:307)
        at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate$default(PathExtensions.kt:304)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.getOrLoadResults(SpanModelFitExperiment.kt:409)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.access$getOrLoadResults(SpanModelFitExperiment.kt:329)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$results$2.invoke(SpanModelFitExperiment.kt:348)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$results$2.invoke(SpanModelFitExperiment.kt:329)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.getResults(SpanModelFitExperiment.kt)
        at org.jetbrains.bio.span.SpanCLA$peakCallingResults$1.invoke(SpanCLA.kt:748)
        at org.jetbrains.bio.span.SpanCLA$peakCallingResults$1.invoke(SpanCLA.kt:41)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.bio.span.SpanCLA$analyze$$inlined$with$lambda$1.invoke(SpanCLA.kt:160)
        at org.jetbrains.bio.span.SpanCLA$analyze$$inlined$with$lambda$1.invoke(SpanCLA.kt:41)
        at org.jetbrains.bio.util.OptionParserExtensionsKt.parse(OptionParserExtensions.kt:70)
        at org.jetbrains.bio.util.OptionParserExtensionsKt.parse$default(OptionParserExtensions.kt:26)
        at org.jetbrains.bio.span.SpanCLA.analyze(SpanCLA.kt:130)
        at org.jetbrains.bio.span.SpanCLA.main(SpanCLA.kt:86)
Caused by: kotlin.KotlinNullPointerException
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at org.jetbrains.bio.viktor.F64Array.getV(F64Array.kt)
        at org.jetbrains.bio.statistics.hmm.HMMInternals.logBackward(Internals.kt:83)
        at org.jetbrains.bio.statistics.hmm.HMMIterationContext$expect$2.run(HMMIterationContext.kt:48)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
        at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
        at org.jetbrains.bio.statistics.hmm.HMMIterationContext.expect(HMMIterationContext.kt:40)
        at org.jetbrains.bio.statistics.IterationContext.iterate(ClassificationModel.kt:301)
        at org.jetbrains.bio.statistics.hmm.MLAbstractHMM$fit$1.invoke(MLAbstractHMM.kt:80)
        at org.jetbrains.bio.statistics.hmm.MLAbstractHMM$fit$1.invoke(MLAbstractHMM.kt:17)
        at org.jetbrains.bio.statistics.hmm.MLAbstractHMM$sam$java_util_function_Consumer$0.accept(MLAbstractHMM.kt)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Exception in thread "main" kotlin.KotlinNullPointerException
        at org.jetbrains.bio.util.OptionParserExtensionsKt.parse(OptionParserExtensions.kt:101)
        at org.jetbrains.bio.util.OptionParserExtensionsKt.parse$default(OptionParserExtensions.kt:26)
        at org.jetbrains.bio.span.SpanCLA.analyze(SpanCLA.kt:130)
        at org.jetbrains.bio.span.SpanCLA.main(SpanCLA.kt:86)
```

**Comment by olegs** [comment]
Cannot reproduce anymore.
