### ISSUE TITLE
Span and Java heap space

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/span#7]
While trying to fit Span for ATAC-seq data, I keep getting an `OutOfMemoryError`:
```
java.lang.OutOfMemoryError: Java heap space
	at org.jetbrains.bio.viktor.F64Array$Companion.invoke(F64Array.kt:671)
	at org.jetbrains.bio.statistics.hmm.MLAbstractHMM.updateParameters(MLAbstractHMM.kt:207)
	at org.jetbrains.bio.statistics.hmm.MLAbstractHMM.fit(MLAbstractHMM.kt:93)
	at org.jetbrains.bio.statistics.Fitter$DefaultImpls.fit(ClassificationModel.kt:184)
	at org.jetbrains.bio.statistics.hmm.MLFreeNBHMM$Companion$fitter$1.fit(MLFreeNBHMM.kt:59)
	at org.jetbrains.bio.statistics.hmm.MLFreeNBHMM$Companion$fitter$1.fit(MLFreeNBHMM.kt:59)
	at org.jetbrains.bio.experiments.fit.SpanPeakCallingExperiment$Companion$semanticCheck$1.fit(SpanPeakCallingExperiment.kt:113)
	at org.jetbrains.bio.experiments.fit.SpanPeakCallingExperiment$Companion$semanticCheck$1.fit(SpanPeakCallingExperiment.kt:99)
	at org.jetbrains.bio.statistics.Fitter$DefaultImpls.fit$default(ClassificationModel.kt:179)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.calculateModel(SpanModelFitExperiment.kt:210)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.access$calculateModel(SpanModelFitExperiment.kt:171)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$getOrLoadResults$1.invoke(SpanModelFitExperiment.kt:251)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$getOrLoadResults$1.invoke(SpanModelFitExperiment.kt:171)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$$special$$inlined$time$lambda$1.invoke(PathExtensions.kt:325)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$$special$$inlined$time$lambda$1.invoke(PathExtensions.kt)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt:465)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt)
	at org.jetbrains.bio.util.LockManager.synchronized(LockManager.kt:38)
	at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate(PathExtensions.kt:306)
	at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate$default(PathExtensions.kt:303)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.getOrLoadResults(SpanModelFitExperiment.kt:248)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.access$getOrLoadResults(SpanModelFitExperiment.kt:171)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$results$2.invoke(SpanModelFitExperiment.kt:187)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment$results$2.invoke(SpanModelFitExperiment.kt:171)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.getResults(SpanModelFitExperiment.kt)
	at org.jetbrains.bio.experiments.fit.SpanModelFitExperiment.doCalculations(SpanModelFitExperiment.kt:193)
	at org.jetbrains.bio.experiments.Experiment.run(Experiment.kt:46)
	at org.jetbrains.bio.span.SpanCLA$analyze$$inlined$with$lambda$1.invoke(SpanCLA.kt:224)
	at org.jetbrains.bio.span.SpanCLA$analyze$$inlined$with$lambda$1.invoke(SpanCLA.kt:35)
	at org.jetbrains.bio.util.OptionParserExtensionsKt.parse(OptionParserExtensions.kt:39)
	at org.jetbrains.bio.util.OptionParserExtensionsKt.parse$default(OptionParserExtensions.kt:15)
```

Curiously, I only get this error when two `Span`s are launched concurrently.
Invocation parameters:
```bash
$ java -Xmx4G -jar bin/span-0.9.2.jar analyze -t <bam> --workdir cleaned_cell_peaks/span --bin 100 --cs hg19.chrom.sizes --threads 8
```
The server has 24 cores and 200G RAM.

**Comment by olegs** [comment]
Probably server was overloaded by BS-Seq alignment at the moment?

**Comment by dievsky** [comment]
I thought BS-seq was running on `franklin`? This problem happens on `rosalind`.

**Comment by dievsky** [comment]
The problem is quite reproducible. Interestingly, it happens each time when a second Span is launched after the first one finishes (I no longer launch them concurrently), but not if it's the first Span instance in the pipeline.

**Comment by olegs** [comment]
Closing as obsolete.
